### ISSUE TITLE
How can I get the data and labels?

### ISSUE THREAD

**Issue by Blcony** [adalca/patchRegistration#2]
Hi, Dalca~
Thanks for your wonderful work and codes!
I have a question that how I can get the clinical images and corresponding manual segmentations mentioned in paper?
I hope to hear from you soon~

**Comment by adalca** [comment]
Unfortunately, we cannot share the data we work with due to the design of the study. However, the ADNI1 T2-FLAIR images are comparable protocols, and these images are public as part o fthe ADNI dataset through LONI: http://adni.loni.usc.edu/. If you are looking to use real sparse-slice images, I recommend using these.
