### ISSUE TITLE
How to use your code to register 2 tiff images? 

### ISSUE THREAD

**Issue by MahsaPaknezhad** [adalca/patchRegistration#3]
Hi!
I am trying to use your code to register two histology images. The inputs to the function registerNii are two files named paths.ini and params.ini. I had a look at the parameters in the paths file to change them to refer to my fixed and moving images. However, the paths.ini file seems to be an example input file for registering the images to an atlas. I don't know how I should change this file to perform registration for my pair of images. Would you please guide me in this process? I appreciate that.

**Comment by andreea7b** [comment]
Hi Mahsa,

Thank you for reaching out with your question! First, you would need to convert your tiff images to nii files. An example for how to do that can be found [here](https://github.com/SainsburyWellcomeCentre/aMAP/wiki/Converting-.tif-to-.nii-using-Matlab).
Then, you would change the fixed and moving image paths to the absolute paths of the new nii images you will have created. You also need to provide masks for your images representing which voxels are missing or not (see Figure 2 in the paper). Lastly, you have two options: `<params.scale.method == resize>` or `<params.scale.method == load>`. If you choose resize, these four niis are all you need (we downsampled our images 7 times, then upsampled them 7 times, which is why our files contain the substring "ds7_us7"). If you choose the option `<params.scale.method == load>` instead, the algorithm loads in rescalings of your images instead of producing them automatically, so you will have to provide scale files (movingScales, movingMaskScales, fixedScales, fixedMaskScales). For our example, we first downsample our images 7 times, then upsample them incrementally 1 to 7 times; thus, paths.ini contains 7 ds7_usx files per image. Notice that if you don't have an atlas (as is your case), fixedMaskScales must be provided as well. As a summary, if you choose `<params.scale.method == resize>`, you need 4 nii files (your two images ds7_us7 -- downsampled and upsampled 7 times -- + their two corresponding masks, also ds7_us7); if you choose `<params.scale.method == load>`, you would need 28 images (upsamplings at 7 levels for each of the
4 nii files).

Hope this helps answer your question!
Andreea

**Comment by MahsaPaknezhad** [comment]
Dear Andreea,
Thank you so much for your reply. I managed to modify the code to receive 2D images as input. However, during the registration process I get the following error:

>> registerNii('E:/patchBasedMatlab/patchRegistration/configs/paths.ini', 'E:/patchBasedMatlab/patchRegistration/configs/params.ini')
9       [vols, paths, params] = niftireg.parseInputs(varargin{:});
Starting: scale 1 iter 1 size 16 16 
Warning: disp2warp: Found 270 (52.73%) NANs . Inpainting. 
scale 1 iter 1 finished in 0.12 sec
Starting: scale 1 iter 2 size 16 16 
Warning: disp2warp: Found 270 (52.73%) NANs . Inpainting. 
scale 1 iter 2 finished in 0.12 sec
Starting: scale 1 iter 3 size 16 16 
Warning: disp2warp: Found 270 (52.73%) NANs . Inpainting. 
scale 1 iter 3 finished in 0.12 sec
Starting: scale 2 iter 1 size 181 128 
Error using patchmrf_PR (line 58)
UGMLBP: Bad nodeBel.
Error in patchreg.mrfWarpReg (line 36)
    [quiltedPatches, ~, ~, ~, quiltedpIdx] = ...
Error in patchreg.singlescale (line 80)
            [warp, quiltedPatches, quiltedpIdx] = patchreg.mrfWarpReg(movingSize, patches, pDst, pIdx,...
Error in patchreg.multiscale (line 50)
            localDispl = patchreg.singlescale(scvolsw, locparams, 'currentdispl', displ, varargin{:});
Error in registerNii (line 12)
    displ = patchreg.multiscale(vols, params);
>> 
I was wondering if you have any idea why I get this error? Really appreciate your help.

Best wishes,
Mahsa

**Comment by adalca** [comment]
It sounds like the output of the MRF inference method in [patchmrf](https://github.com/adalca/patchRegistration/blob/2ffa6c4438071c1aca3b12d5fc53d515a16b92e2/src/tools/mrf/patchmrf_PR.m#L57 ) has Nans. Could you take a look at that line and maybe look at the `nodeBel` output, and what the inputs are, especialy `inputs.inferMethod`? it would help figure out what part is failing.

**Comment by MahsaPaknezhad** [comment]
Dear Adrian,
Thank you for your reply. It seems like the registration carries out successfully when I rescale the image intensity to the [0, 1] range. Appreciate your cooperation.

Best Wishes,
Mahsa
